# Generated by Django 3.0.6 on 2021-05-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.CharField(default='', max_length=132)),
                ('video_name', models.CharField(default='', max_length=32)),
                ('video_data', models.CharField(default='', max_length=32)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.UserModel')),
            ],
            options={
                'verbose_name': '视频表',
                'verbose_name_plural': '视频表',
                'db_table': 'video',
            },
        ),
        migrations.DeleteModel(
            name='FiveDayModel',
        ),
        migrations.DeleteModel(
            name='TenDayModel',
        ),
        migrations.DeleteModel(
            name='ThreeDayModel',
        ),
        migrations.DeleteModel(
            name='TodayModel',
        ),
    ]
