# Generated by Django 3.2.3 on 2021-05-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_auto_20210519_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShejiXuanti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('production_url', models.CharField(default='', max_length=132)),
                ('production_name', models.CharField(default='', max_length=32)),
                ('add_time', models.IntegerField(blank=True, default=0, verbose_name='添加时间')),
                ('update_time', models.IntegerField(blank=True, default=0, verbose_name='修改时间')),
                ('mark', models.IntegerField(blank=True, default=0, verbose_name='打分')),
            ],
            options={
                'verbose_name': '选题信息表',
                'verbose_name_plural': '选题信息表',
                'db_table': 'xuanti',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='学号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('permission', models.CharField(max_length=24, verbose_name='权限')),
                ('nickname', models.CharField(default='', max_length=24, verbose_name='昵称')),
                ('login_time', models.IntegerField(blank=True, default=0, verbose_name='登录时间')),
                ('reg_time', models.IntegerField(blank=True, default=0, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'a_student',
            },
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': '管理员老师表', 'verbose_name_plural': '管理员老师表'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(default='', max_length=24, verbose_name='昵称'),
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='a_teacher',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='shejixuanti',
            name='student_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.studentmodel'),
        ),
        migrations.AddField(
            model_name='shejixuanti',
            name='teacher_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.usermodel'),
        ),
    ]
