# Generated by Django 3.2.3 on 2021-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_auto_20210526_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='online',
            field=models.SmallIntegerField(default=0, verbose_name='是否在线'),
        ),
    ]
