# Generated by Django 3.2.3 on 2021-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_studentmodel_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shejixuanti',
            name='mark',
            field=models.CharField(default='', max_length=32, verbose_name='打分'),
        ),
    ]
