# Generated by Django 3.2.3 on 2021-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_alter_shejixuanti_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='shejixuanti',
            name='headline',
            field=models.CharField(default='', max_length=32, verbose_name='选题标题'),
        ),
        migrations.AddField(
            model_name='shejixuanti',
            name='remark',
            field=models.CharField(default='', max_length=3132, verbose_name='老师的评语'),
        ),
    ]
