# Generated by Django 3.2.3 on 2021-05-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_auto_20210527_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(default='', max_length=24, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='', max_length=24, verbose_name='用户名'),
        ),
    ]
