# Generated by Django 3.2.3 on 2021-05-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_auto_20210527_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(default='', max_length=24, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=24, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
    ]
