# Generated by Django 3.2.3 on 2021-05-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_auto_20210527_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.IntegerField(blank=True, default=0, verbose_name='添加时间')),
                ('update_time', models.IntegerField(blank=True, default=0, verbose_name='修改时间')),
                ('paper_headline', models.CharField(default='', max_length=32, verbose_name='选题标题')),
            ],
            options={
                'verbose_name': '论文题目表',
                'verbose_name_plural': '论文题目表',
                'db_table': 'title',
            },
        ),
    ]
