# Generated by Django 3.2.3 on 2021-08-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dogstype', models.CharField(max_length=128, unique=True, verbose_name='宠物类型')),
                ('dogsname', models.CharField(max_length=128, verbose_name='宠物名称')),
                ('permission', models.CharField(max_length=24, verbose_name='权限')),
                ('dogsdesc', models.CharField(default='', max_length=24, verbose_name='宠物描述')),
                ('login_time', models.IntegerField(blank=True, default=0, verbose_name='登录时间')),
                ('reg_time', models.IntegerField(blank=True, default=0, verbose_name='注册时间')),
                ('online', models.SmallIntegerField(default=0, verbose_name='是否在线')),
            ],
            options={
                'verbose_name': '小鸟表',
                'verbose_name_plural': '小鸟表',
                'db_table': 'birds',
            },
        ),
        migrations.CreateModel(
            name='CatsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dogstype', models.CharField(max_length=128, unique=True, verbose_name='宠物类型')),
                ('dogsname', models.CharField(max_length=128, verbose_name='宠物名称')),
                ('permission', models.CharField(max_length=24, verbose_name='权限')),
                ('dogsdesc', models.CharField(default='', max_length=24, verbose_name='宠物描述')),
                ('login_time', models.IntegerField(blank=True, default=0, verbose_name='登录时间')),
                ('reg_time', models.IntegerField(blank=True, default=0, verbose_name='注册时间')),
                ('online', models.SmallIntegerField(default=0, verbose_name='是否在线')),
            ],
            options={
                'verbose_name': '猫咪表',
                'verbose_name_plural': '猫咪表',
                'db_table': 'cats',
            },
        ),
        migrations.CreateModel(
            name='DogsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dogstype', models.CharField(max_length=128, unique=True, verbose_name='宠物类型')),
                ('dogsname', models.CharField(max_length=128, verbose_name='宠物名称')),
                ('permission', models.CharField(max_length=24, verbose_name='权限')),
                ('dogsdesc', models.CharField(default='', max_length=24, verbose_name='宠物描述')),
                ('login_time', models.IntegerField(blank=True, default=0, verbose_name='登录时间')),
                ('reg_time', models.IntegerField(blank=True, default=0, verbose_name='注册时间')),
                ('online', models.SmallIntegerField(default=0, verbose_name='是否在线')),
            ],
            options={
                'verbose_name': '狗狗表',
                'verbose_name_plural': '狗狗表',
                'db_table': 'dogs',
            },
        ),
        migrations.CreateModel(
            name='RabbitsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dogstype', models.CharField(max_length=128, unique=True, verbose_name='宠物类型')),
                ('dogsname', models.CharField(max_length=128, verbose_name='宠物名称')),
                ('permission', models.CharField(max_length=24, verbose_name='权限')),
                ('dogsdesc', models.CharField(default='', max_length=24, verbose_name='宠物描述')),
                ('login_time', models.IntegerField(blank=True, default=0, verbose_name='登录时间')),
                ('reg_time', models.IntegerField(blank=True, default=0, verbose_name='注册时间')),
                ('online', models.SmallIntegerField(default=0, verbose_name='是否在线')),
            ],
            options={
                'verbose_name': '兔子表',
                'verbose_name_plural': '兔子表',
                'db_table': 'rabbits',
            },
        ),
    ]
